version: "4.19"
services:
  proyectos-back:
    container_name: backend-proyecto-micro
    image: backend-proyecto-micro:v1
    build:
      context: .
    ports:
      - "4007"
    networks:
      - proyectos-app

  proyecto-back-2:
    container_name: backend-proyecto-micro-2
    image: backend-proyecto-micro:v1
    build:
      context: .
    ports:
      - "4007"
    networks:
      - proyectos-app

  proyecto-back-3:
    container_name: backend-proyecto-micro-3
    image: backend-proyecto-micro:v1
    build:
      context: .
    ports:
      - "4007"
    networks:
      - proyectos-app

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectos-app

networks:
  proyectos-app:
